<a href="https://colab.research.google.com/github/eceirem/Patika/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY



In [2]:
import numpy as np

## Array yaratmak


Python listlerine benzeyen, aynı tipten çok sayıda elemanı içeren, hızlı işlem yapılmasını sağlayan kavramlardır.

In [ ]:
x= np.array([1,2,3,4])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
x = np.array(["4.2"], dtype="int32") #geçersiz bir işlem

In [ ]:
x

array([4.2])

In [ ]:
np.full(2,3)

array([3, 3])

In [ ]:
type(x)

In [ ]:
c = np.array(['30',20,64,"s",6.2]) #stringi tercih eder burada
#her int ve float str'ye cast edilebilir

In [ ]:
c

array(['30', '20', '64', 's', '6.2'], dtype='<U32')

In [ ]:
m= np.array(["a","b","c"])

In [ ]:
m

In [ ]:
n= np.array([1,2,3,"a"])

In [ ]:
# eğer arrayin içinde bir tane bile karakter varsa; elemanlar, arrayın içinde string tipinde tutulur.
n

In [ ]:
# 1 tane float olduğu için dğer integerlar da floata dönüştü
z= np.array([1,2,3,3.5])

In [ ]:
z

## Array data tipini belirleme

In [ ]:
x=np.array([1,2,3.4])

In [ ]:
x

In [ ]:
x=np.array([1,2,3.6], dtype="int32")   #arrayin tipini integer yapma

In [ ]:
x

In [ ]:
y=np.array([1,2,3.4], dtype="str") #arrayin tipini str yapma

In [ ]:
y

In [ ]:
y=np.array([1,2,3.47], dtype="int16")  #str olduğu için integer hale getiremeyiz.

In [ ]:
y

## Elemanları 0 olan array

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#3 satır(row) ve 5 sütun(kolon)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 2 boyutlu 3x5 lik array matris
x= np.zeros([3,5])
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 3 boyutlu
# 4 tane 5x7 lik array kur
y= np.zeros([4,5,7])
y

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

## array bilgilerine erişme

In [ ]:
x.shape

(3, 5)

In [ ]:
y.shape

(4, 5, 7)

In [ ]:
#boyut
x.ndim

2

In [ ]:
#boyut
y.ndim

3

In [ ]:
#array içindeki eleman (3*5)
x.size

15

In [ ]:
y.size #(4*5*7)

140

### np.full

In [ ]:
# 3x5 lik elemanları 7 olan array
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.full((3,5),7, dtype="int32")

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int32)

In [ ]:
np.full((3,5),"m")

array([['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm']], dtype='<U1')

### ardışık sayılardan array

In [ ]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(0,14,2) # 2 atlamalı şekilde 14'e kadar array oluşturdu

array([ 0,  2,  4,  6,  8, 10, 12])

## aralığı eşit uzaklıkta bölerek array oluşturma

verilen başlangıç ve bitiş noktasına göre, başlangıç ve bitiş noktası da dahil, aradaki sayıları eşit uzaklıkta olacak şekilde yazarak oluşturur. (linspace)

In [ ]:
#default olarak aradaki mesafeyi 50 nokta olacak şekilde yazar
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
np.linspace(1,2).ndim

1

In [ ]:
#num=3 ile 1-2 arasındaki mesafeyi kendileri dahil 3'e bölüyor.
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [ ]:
np.linspace(1.5,3, num=3)

array([1.5 , 2.25, 3.  ])

## Normal Dağılıma Uygun değerler ile array oluşturma

In [ ]:
#np.random.normal(mean, std, array, shape) şeklinde

In [ ]:
np.random.normal(10,3, (3,5))
#0 ortalamalı, standart sapması 1 olacak şekilde (3x5)lik
#bir normal dağılıma uygun array oluşturduk

array([[16.87179049, 14.6026017 , 12.37896151,  9.70173747, 10.52043345],
       [ 9.26453146,  6.93093826, 12.82390406, 13.26913645,  9.49492439],
       [11.07006368,  9.02883531,  9.67006901,  6.21280103,  8.7612059 ]])

In [ ]:
np.random.normal(0,100, (3,5))

array([[ -50.02140171,    6.41623422,   62.04574923,   -6.06718225,
         -77.95775937],
       [ -65.24335184,   20.10599295,  138.8789697 ,   20.66213741,
        -157.66138393],
       [ -78.37072975,  -88.74088993,  -16.38757383,  220.66506015,
         -25.6610091 ]])

In [ ]:
np.random.normal(0,10, (2,2))

array([[-17.86636042,  -1.36931361],
       [  6.45700605,  -8.66615448]])

## Random Integer'lar ile Array Oluşturmak

In [ ]:
# np.random.randint(low,high)
# 15 dahil değil

np.random.randint(1,15,(3,5))

array([[14,  8,  8, 10,  5],
       [ 5, 10,  5, 12,  2],
       [ 6,  1, 13, 13,  4]])

In [ ]:
np.random.randint(5,15,(3,5))

array([[ 6,  8,  5, 11,  8],
       [ 8,  7,  8,  6, 10],
       [ 5, 13, 12,  9,  9]])

## Birim Matris Oluşturmak

In [ ]:
# birim array yaratma (köşegenleri 1 olan diğer elemanları 0 olan array)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Array Matematiksel İşlemler

In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
np.array([3,5,9])*3

array([ 9, 15, 27])

In [ ]:
x*y

array([ 4, 10, 18])

In [ ]:
x+y

array([5, 7, 9])

In [ ]:
print(x+y)

[5 7 9]


In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6,8])

x*y  #(arraylar birbirine denk olmadığı için hata aldık)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
#note: listede toplama işlemi tanımlı değil
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a
#ndim dediğimiz boyuttur. 2D bir array bu
#shape ise (satır, sütun) sayısını verir
#size ise toplam eleman sayısıdır.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x.size

1

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#her bir değerin karekökünü aldı
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
#matris gibi çarpım yapar.
#(dot) (shapelerin aynı olmasına gerek yoktur)

a1 = np.array([[1,2],
               [2,0],
               [3,1]])

a2 = np.array ([[4,3],
                [1,2]])

print(np.dot(a1,a2))

[[ 6  7]
 [ 8  6]
 [13 11]]


## Reshape

In [ ]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m.reshape(2,5) # 2*5 = 10 olduğundan ve 10=m olduğundan hatasız çalışır

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
m.reshape(3,5) #3*5= 15 olduğundan 15!= m olduğundan hata aldık.

ValueError: cannot reshape array of size 10 into shape (3,5)

In [ ]:
# eleman sayısı ile reshape içindeki (satır * sütunun) aynısı olması gerekldiri reshape için
m.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [ ]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
n.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

##-1 ile Boyuta Karar Vermek

In [ ]:
#otomatik olarak 4 kolonlu bir array yarattı
#ben 4 kolon olsun diyorum satırına sen karar ver
n.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
n.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## Yeni Boyuta Karar Vermek

In [ ]:
a = np.arange(1,11)
print(a)
print(a.shape)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
1


In [ ]:
a[np.newaxis,:]
print(a)
print(a.shape)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
1


# concatenate

In [ ]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
l=[9.2,0]

In [ ]:
np.concatenate([y,x,l]) #bir tanesi float ise hepsi float olur

array([4. , 5. , 6. , 1. , 2. , 3. , 9.2, 0. ])

In [ ]:
# iki boyutlu

a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
#dimensionların aynı olması gerekir
m= np.concatenate([a,a])
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#asis = 0 satır boyunca
#yani satır altına yazar
m= np.concatenate([a,a],axis=0)
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#axis= 1 sutun boyunca işlem
#yani satırda yana ekler
m= np.concatenate([a,a],axis=1)
m

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Stack

In [ ]:
a = np.array([1,2,3])
b = np.array([5,6,7])

In [ ]:
a.shape
b.shape

(3,)

In [ ]:
x = np.stack([a,b])

In [ ]:
x.shape

(2, 3)

In [ ]:
y = np.stack([a,b],axis=1)

In [ ]:
y

array([[1, 5],
       [2, 6],
       [3, 7]])

# Splitting

In [ ]:
l=[10,20,30,40,50,60,70,80] #list

In [ ]:
l[0:5]

[10, 20, 30, 40, 50]

In [ ]:
l[:5]

[10, 20, 30, 40, 50]

In [ ]:
final=np.split(l,[2,5])
final

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

In [ ]:
a,b,c=final

In [ ]:
a,b,c=np.split(l,[2,5])

In [ ]:
a

array([10, 20])

In [ ]:
b

array([30, 40, 50])

In [ ]:
c

array([60, 70, 80])

# Array elemanlarına erişmek

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#birinci satır
a[0]

array([1, 2, 3, 4])

In [ ]:
# ikinci satır
a[1]

array([5, 6, 7, 8])

In [ ]:
#0.satır 0.kolon
a[0,0]

np.int64(1)

In [ ]:
#0.satır 0.kolon
a[0][0]

np.int64(1)

In [ ]:
#0.satır 1.kolon
a[0,1]

np.int64(2)

In [ ]:
a[1,1]

np.int64(6)

In [ ]:
#2.satır 2.kolon
a[2,2]

np.int64(11)

In [ ]:
#2.satır 2.kolon 300 olarak değiştirildi
a[2,2]= 300
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 300,  12]])

### Slice indeksing

In [ ]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 0 satırı ile 2. satır arasındaki satırları yazdı. (2.satır dahil değil)
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:] # bütün satır ve sütünu alır

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#bütün satırları al ama 2.indexteki kolonu al
a[:,2]

array([ 3,  7, 11])

In [ ]:
#bütün satırları al ama 0'dan 2. kolona kadar olan sütünları al
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
#bütün satırları ve bütün kolonlaru al
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[0:2,2]

array([3, 7])

In [ ]:
a = np.arange(20)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a = a.reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.vsplit(a,[2,3]) #vertical satırda kestim

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# filter

In [ ]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a<7

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [ ]:
# 7 den küçük değerlere ulaştık
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
filt= a<5

In [ ]:
a[filt]

array([1, 2, 3, 4])

In [ ]:
#array tipinde and = &
filt= (a>5) & (a<9)

In [ ]:
a[filt]

array([6, 7, 8])

In [ ]:
#array tipinde or = |
filt= (a<5) | (a>8)

In [ ]:
a[filt]

array([1, 2, 3, 4, 9])

In [ ]:
#filtrenin değili (a<5 dışında kalanlar)
filt= ~(a<5)

In [ ]:
a[filt]

array([5, 6, 7, 8, 9])

In [ ]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
#filtre boyutu bozar. istenirse sonra tekrardan boyut eklenebilir.
b[b<7]

array([1, 2, 3, 4, 5, 6])

In [ ]:
b[b<7].reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 7 den küçük elanlar ile oluşturulan altküme bir array
x= b[b<7].reshape(2,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

## Sort

In [3]:
x = np.array([2,1,4,3,5])
np.sort(x) #x'i güncellemez

array([1, 2, 3, 4, 5])

In [4]:
x

array([2, 1, 4, 3, 5])

In [7]:
x.sort() #x'i sıralar ve üzerine yazar

In [8]:
x

array([1, 2, 3, 4, 5])

# Indexing

In [9]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
a[0]

array([1, 2, 3, 4, 5])

In [14]:
a[0,0] #a[0][0] aynıdır

np.int64(1)

In [15]:
a[1,1] = 20.40 #dizi bir int dizisi, bu yüzden cast eder

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
a[1,1] = '222'

In [20]:
a

array([[  1,   2,   3,   4,   5],
       [  6, 222,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [21]:
a[0:3]

array([[  1,   2,   3,   4,   5],
       [  6, 222,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [22]:
a[1:2]

array([[  6, 222,   8,   9,  10]])

In [23]:
a[:,2] #tüm değerleri al ama satırlardan ama 3. sütunu al

array([ 3,  8, 13, 18])

In [24]:
a[0,2:4] #0. satırın 2 ile 4 arasını al

array([3, 4])

In [25]:
a[:2,:3]

array([[  1,   2,   3],
       [  6, 222,   8]])

In [26]:
a[::,:4]

array([[  1,   2,   3,   4],
       [  6, 222,   8,   9],
       [ 11,  12,  13,  14],
       [ 16,  17,  18,  19]])

#Fancy Indexing


In [30]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
idxs = [3,4,5,6]

In [32]:
b[idxs]

array([4, 5, 6, 7])

In [55]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
a[0:2,1] #bir tarafta sayı varsa shape bozulur

array([2, 7])

In [57]:
a[0:2,1:2] #iki taraf da slicing olunca shape korunur

array([[2],
       [7]])

In [58]:
idx1 = [1,3,2]
idx2 = [3,0,2]

In [59]:
a[idx1,idx2] # a[1][3],a[3][0],a[2][2] demek bu
#yine shape özelliği bozuldu

array([ 9, 16, 13])

In [60]:
a[idx1,idx2].shape #sayı öbeği döndürür

(3,)

In [61]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
ece = np.arange(9)

In [65]:
ece

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
ece[[1,2,3]] = 20

In [67]:
ece

array([ 0, 20, 20, 20,  4,  5,  6,  7,  8])

In [68]:
ece[[1,2,3]] = [10,20,30]

In [69]:
ece

array([ 0, 10, 20, 30,  4,  5,  6,  7,  8])

# SUM

In [ ]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#bütün elemanları topluyor.
np.sum(b)

np.int64(45)

In [ ]:
#7'den küçük olanların toplamı
np.sum(b[b<7])

np.int64(21)

In [ ]:
# sütunların toplamı
np.sum(b,axis=0)

array([12, 15, 18])

In [ ]:
# satırların toplamı
np.sum(b,axis=1)

array([ 6, 15, 24])