<a href="https://colab.research.google.com/github/eceirem/Patika/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NUMPY



In [ ]:
import numpy as np

## Array yaratmak


Python listlerine benzeyen, aynı tipten çok sayıda elemanı içeren, hızlı işlem yapılmasını sağlayan kavramlardır.

In [ ]:
x= np.array([1,2,3,4])

In [ ]:
x

In [ ]:
type(x)

In [ ]:
m= np.array(["a","b","c"])

In [ ]:
m

In [ ]:
n= np.array([1,2,3,"a"])

In [ ]:
# eğer arrayin içinde bir tane bile karakter varsa; elemanlar, arrayın içinde string tipinde tutulur.
n

In [ ]:
# 1 tane float olduğu için dğer integerlar da floata dönüştü
z= np.array([1,2,3,3.5])

In [ ]:
z

## Array data tipini belirleme

In [ ]:
x=np.array([1,2,3.4])

In [ ]:
x

In [ ]:
x=np.array([1,2,3.6], dtype="int32")   #arrayin tipini integer yapma

In [ ]:
x

In [ ]:
y=np.array([1,2,3.4], dtype="str") #arrayin tipini str yapma

In [ ]:
y

In [ ]:
y=np.array([1,2,3.47], dtype="int16")  #str olduğu için integer hale getiremeyiz.

In [ ]:
y

## Elemanları 0 olan array

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
#3 satır(row) ve 5 sütun(kolon)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# 2 boyutlu 3x5 lik array matris
x= np.zeros([3,5])
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# 3 boyutlu
# 4 tane 5x7 lik array kur
y= np.zeros([4,5,7])
y

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

## array bilgilerine erişme

In [34]:
x.shape

(3, 5)

In [35]:
y.shape

(4, 5, 7)

In [36]:
#boyut
x.ndim

2

In [37]:
#boyut
y.ndim

3

In [38]:
#array içindeki eleman (3*5)
x.size

15

In [39]:
y.size #(4*5*7)

140

### np.full

In [41]:
# 3x5 lik elemanları 7 olan array
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [40]:
np.full((3,5),7, dtype="int32")

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int32)

In [42]:
np.full((3,5),"m")

array([['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm']], dtype='<U1')

### ardışık sayılardan array

In [43]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
np.arange(0,14,2) # 2 atlamalı şekilde 14'e kadar array oluşturdu

array([ 0,  2,  4,  6,  8, 10, 12])

## aralığı eşit uzaklıkta bölerek array oluşturma

verilen başlangıç ve bitiş noktasına göre, başlangıç ve bitiş noktası da dahil, aradaki sayıları eşit uzaklıkta olacak şekilde yazarak oluşturur. (linspace)

In [45]:
#default olarak aradaki mesafeyi 50 nokta olacak şekilde yazar
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [46]:
np.linspace(1,2).ndim

1

In [48]:
#num=3 ile 1-2 arasındaki mesafeyi kendileri dahil 3'e bölüyor.
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [49]:
np.linspace(1.5,3, num=3)

array([1.5 , 2.25, 3.  ])

## Normal Dağılıma Uygun değerler ile array oluşturma

In [ ]:
#np.random.normal(mean, std, array, shape) şeklinde

In [58]:
np.random.normal(10,3, (3,5))
#0 ortalamalı, standart sapması 1 olacak şekilde (3x5)lik
#bir normal dağılıma uygun array oluşturduk

array([[16.87179049, 14.6026017 , 12.37896151,  9.70173747, 10.52043345],
       [ 9.26453146,  6.93093826, 12.82390406, 13.26913645,  9.49492439],
       [11.07006368,  9.02883531,  9.67006901,  6.21280103,  8.7612059 ]])

In [56]:
np.random.normal(0,100, (3,5))

array([[ -50.02140171,    6.41623422,   62.04574923,   -6.06718225,
         -77.95775937],
       [ -65.24335184,   20.10599295,  138.8789697 ,   20.66213741,
        -157.66138393],
       [ -78.37072975,  -88.74088993,  -16.38757383,  220.66506015,
         -25.6610091 ]])

## Random olarak

In [59]:
# np.random.randint(low,high)
# 15 dahil değil

np.random.randint(1,15,(3,5))

array([[14,  8,  8, 10,  5],
       [ 5, 10,  5, 12,  2],
       [ 6,  1, 13, 13,  4]])

In [61]:
np.random.randint(5,15,(3,5))

array([[ 6,  8,  5, 11,  8],
       [ 8,  7,  8,  6, 10],
       [ 5, 13, 12,  9,  9]])

In [62]:
# birim array yaratma (köşegenleri 1 olan diğer elemanları 0 olan array)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Array Matematiksel İşlemler

In [64]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [65]:
x*y

array([ 4, 10, 18])

In [66]:
x+y

array([5, 7, 9])

In [67]:
print(x+y)

[5 7 9]


In [68]:
x= np.array([1,2,3])
y= np.array([4,5,6,8])

x*y  #(arraylar birbirine denk olmadığı için hata aldık)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [69]:
#note: listede toplama işlemi tanımlı değil
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [70]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a.ndim

2

In [72]:
a.shape

(2, 3)

In [73]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [74]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [75]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [77]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
#her bir değerin karekökünü aldı
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [80]:
#matris gibi çarpım yapar.
#(dot) (shapelerin aynı olmasına gerek yoktur)

a1 = np.array([[1,2],
               [2,0],
               [3,1]])

a2 = np.array ([[4,3],
                [1,2]])

print(np.dot(a1,a2))

[[ 6  7]
 [ 8  6]
 [13 11]]


## Reshape

In [81]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
m.reshape(2,5) # 2*5 = 10 olduğundan ve 10=m olduğundan hatasız çalışır

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
m.reshape(3,5) #3*5= 15 olduğundan 15!= m olduğundan hata aldık.

ValueError: cannot reshape array of size 10 into shape (3,5)

In [84]:
# eleman sayısı ile reshape içindeki (satır * sütunun) aynısı olması gerekldiri reshape için
m.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [85]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
n.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
#otomatik olarak 4 kolonlu bir array yarattı
n.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# concatenate

In [89]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [90]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [91]:
l=[9,0]

In [92]:
np.concatenate([y,x,l])

array([4, 5, 6, 1, 2, 3, 9, 0])

In [93]:
# iki boyutlu

a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
a.ndim

2

In [95]:
a.shape

(2, 3)

In [96]:
#dimensionların aynı olması gerekir
m= np.concatenate([a,a])
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [99]:
#asis = 0 satır boyunca
#yani satır altına yazar
m= np.concatenate([a,a],axis=0)
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [98]:
#axis= 1 sutun boyunca işlem
#yani satırda yana ekler
m= np.concatenate([a,a],axis=1)
m

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting

In [100]:
l=[10,20,30,40,50,60,70,80] #list

In [101]:
l[0:5]

[10, 20, 30, 40, 50]

In [102]:
l[:5]

[10, 20, 30, 40, 50]

In [106]:
final=np.split(l,[2,5])
final

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

In [107]:
a,b,c=final

In [108]:
a,b,c=np.split(l,[2,5])

In [109]:
a

array([10, 20])

In [110]:
b

array([30, 40, 50])

In [111]:
c

array([60, 70, 80])

# Array elemanlarına erişmek

In [114]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
#birinci satır
a[0]

array([1, 2, 3, 4])

In [116]:
# ikinci satır
a[1]

array([5, 6, 7, 8])

In [117]:
#0.satır 0.kolon
a[0,0]

np.int64(1)

In [118]:
#0.satır 0.kolon
a[0][0]

np.int64(1)

In [119]:
#0.satır 1.kolon
a[0,1]

np.int64(2)

In [120]:
a[1,1]

np.int64(6)

In [121]:
#2.satır 2.kolon
a[2,2]

np.int64(11)

In [122]:
#2.satır 2.kolon 300 olarak değiştirildi
a[2,2]= 300
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 300,  12]])

### Slice indeksing

In [123]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
# 0 satırı ile 2. satır arasındaki satırları yazdı. (2.satır dahil değil)
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
a[:] # bütün satır ve sütünu alır

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
#bütün satırları al ama 2.indexteki kolonu al
a[:,2]

array([ 3,  7, 11])

In [129]:
#bütün satırları al ama 0'dan 2. kolona kadar olan sütünları al
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [130]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [131]:
#bütün satırları ve bütün kolonlaru al
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
a[0:2,2]

array([3, 7])

# filter

In [133]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a<7

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [135]:
# 7 den küçük değerlere ulaştık
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [136]:
filt= a<5

In [137]:
a[filt]

array([1, 2, 3, 4])

In [138]:
#array tipinde and = &
filt= (a>5) & (a<9)

In [139]:
a[filt]

array([6, 7, 8])

In [140]:
#array tipinde or = |
filt= (a<5) | (a>8)

In [141]:
a[filt]

array([1, 2, 3, 4, 9])

In [142]:
#filtrenin değili (a<5 dışında kalanlar)
filt= ~(a<5)

In [143]:
a[filt]

array([5, 6, 7, 8, 9])

In [144]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
b<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [146]:
#filtre boyutu bozar. istenirse sonra tekrardan boyut eklenebilir.
b[b<7]

array([1, 2, 3, 4, 5, 6])

In [147]:
b[b<7].reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
# 7 den küçük elanlar ile oluşturulan altküme bir array
x= b[b<7].reshape(2,3)

In [149]:
x

array([[1, 2, 3],
       [4, 5, 6]])

# SUM

In [150]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
#bütün elemanları topluyor.
np.sum(b)

np.int64(45)

In [152]:
#7'den küçük olanların toplamı
np.sum(b[b<7])

np.int64(21)

In [153]:
# sütunların toplamı
np.sum(b,axis=0)

array([12, 15, 18])

In [154]:
# satırların toplamı
np.sum(b,axis=1)

array([ 6, 15, 24])